"""Integration tests for the draft state machine (WP-07, plan section 6.2).

Uses the FIXTURE set/pack-config so nothing here depends on real IAR data
being present.
"""

from __future__ import annotations

import json
import time
from pathlib import Path
from typing import Any

import pytest
from fabdraft_core.contracts import Card, DraftEvent, PackConfig, SetSnapshot
from fabdraft_core.draft.engine import PickSource, run_draft
from fabdraft_core.draft.events import EventStore
from fabdraft_core.draft.state import DraftState

REPO_ROOT = Path(__file__).resolve().parents[3]
FIXTURE_SET_PATH = REPO_ROOT / "data" / "fixtures" / "fixture_set.json"
FIXTURE_PACK_CONFIG_PATH = REPO_ROOT / "data" / "config" / "fixture.pack_config.json"
IAR_SET_PATH = REPO_ROOT / "data" / "sets" / "IAR.validated.json"
IAR_PACK_CONFIG_PATH = REPO_ROOT / "data" / "config" / "iar.pack_config.json"


@pytest.fixture(scope="module")
def fixture_cards() -> list[Card]:
    return SetSnapshot.model_validate(json.loads(FIXTURE_SET_PATH.read_text())).cards


@pytest.fixture(scope="module")
def fixture_pack_config() -> PackConfig:
    return PackConfig.model_validate(json.loads(FIXTURE_PACK_CONFIG_PATH.read_text()))


class FirstAvailablePickSource:
    """Deterministic, no randomness of its own: always takes the first
    offered card. Good for invariant checks that shouldn't depend on a
    pick source's own decision logic.
    """

    async def get_pick(self, seat: int, pack: list[Card], deadline_ms: int | None) -> str | None:
        return pack[0].uid


class AlwaysTimesOutPickSource:
    async def get_pick(self, seat: int, pack: list[Card], deadline_ms: int | None) -> str | None:
        return None


class InvalidPickSource:
    async def get_pick(self, seat: int, pack: list[Card], deadline_ms: int | None) -> str | None:
        return "not-a-real-uid-in-this-pack"


class SeatSpecificPickSource:
    """Seat `flaky_seat` always uses `flaky_source`; every other seat picks
    the first offered card.
    """

    def __init__(self, flaky_seat: int, flaky_source: PickSource) -> None:
        self._flaky_seat = flaky_seat
        self._flaky_source = flaky_source

    async def get_pick(self, seat: int, pack: list[Card], deadline_ms: int | None) -> str | None:
        if seat == self._flaky_seat:
            return await self._flaky_source.get_pick(seat, pack, deadline_ms)
        return pack[0].uid


async def _run(
    cards: list[Card],
    pack_config: PackConfig,
    pick_source: PickSource,
    seed: str = "test-seed",
) -> tuple[DraftState, EventStore]:
    return await run_draft(
        session_id="test-session",
        seed=seed,
        cards=cards,
        pack_config=pack_config,
        pick_source=pick_source,
    )


async def test_full_draft_drafts_336_cards_42_per_seat(
    fixture_cards: list[Card], fixture_pack_config: PackConfig
) -> None:
    """plan section 6.2: 'sum(len(pool[s])) == 336 at POOL_FINALIZED;
    len(pool[s]) == 42 for all seats.' A card's *uid* can legitimately
    repeat across different players' pools - packs are generated by
    weighted sampling over the whole rarity pool (WP-05), the same way
    real boosters draw from a large print run, so the same Common can
    appear in more than one pack. What must never repeat is a card within
    a *single* pack (WP-05's own `no_duplicate_uids_within_pack` gate,
    covered by test_pack_generator.py) - not across the whole draft.
    """
    state, store = await _run(fixture_cards, fixture_pack_config, FirstAvailablePickSource())
    assert state.phase == "finished"
    pool_sizes = {seat: len(pool) for seat, pool in state.seat_pools.items()}
    assert pool_sizes == {s: 42 for s in range(8)}
    assert sum(pool_sizes.values()) == 336


async def test_each_pack_lineage_is_picked_down_to_empty_with_no_repeats(
    fixture_cards: list[Card], fixture_pack_config: PackConfig
) -> None:
    """The conservation law behind 'every draftable card is picked exactly
    once' (plan section 6.2): for one specific pack_id (e.g. "r1p3"), the
    union of picks made from it is exactly its 14 draftable cards, each
    picked exactly once, across however many seats it visits as it's
    passed and wheeled.
    """
    _, store = await _run(fixture_cards, fixture_pack_config, FirstAvailablePickSource())
    picks_by_pack_id: dict[str, list[str]] = {}
    for e in store.events:
        if e.type in ("PICK_MADE", "PICK_AUTO"):
            picks_by_pack_id.setdefault(e.payload["pack_id"], []).append(e.payload["picked_uid"])
    assert len(picks_by_pack_id) == 24  # 8 seats x 3 rounds
    for pack_id, picks in picks_by_pack_id.items():
        assert len(picks) == 14, f"{pack_id}: expected 14 picks, got {len(picks)}"
        assert len(set(picks)) == 14, f"{pack_id}: a card was picked twice from the same pack"


async def test_pack_sizes_per_seat_per_round_are_14_down_to_1(
    fixture_cards: list[Card], fixture_pack_config: PackConfig
) -> None:
    _, store = await _run(fixture_cards, fixture_pack_config, FirstAvailablePickSource())
    for round_number in (1, 2, 3):
        for seat in range(8):
            sizes = [
                e.payload["pack_size_before"]
                for e in store.events
                if e.type == "PICK_MADE" and e.round == round_number and e.seat == seat
            ]
            assert sizes == list(range(14, 0, -1)), f"round {round_number} seat {seat}: {sizes}"


async def test_wheeling_matches_the_plan_glossary(
    fixture_cards: list[Card], fixture_pack_config: PackConfig
) -> None:
    """plan glossary: 'Wheel: A pack returning to a seat after passing
    around the pod (with 14 cards and 8 seats, picks 9 to 14 come from
    wheeled packs).' This directly contradicts plan section 6.2's own
    stated invariant "a seat never receives the same pack twice within a
    round," which is mathematically impossible for an 8-seat pod with 14
    picks/round - see docs/status/WP-07.md. This test pins the *correct*
    (glossary-consistent) behavior.
    """
    _, store = await _run(fixture_cards, fixture_pack_config, FirstAvailablePickSource())
    pack_ids = [
        e.payload["pack_id"]
        for e in store.events
        if e.type == "PICK_MADE" and e.round == 1 and e.seat == 0
    ]
    assert len(pack_ids) == 14
    first_eight = pack_ids[:8]
    assert len(set(first_eight)) == 8, "picks 1-8 should be 8 distinct packs"
    wheeled = pack_ids[8:]
    assert wheeled == first_eight[:6], "picks 9-14 should wheel back through the first 6 packs"


async def test_pass_direction_is_left_right_left(
    fixture_cards: list[Card], fixture_pack_config: PackConfig
) -> None:
    _, store = await _run(fixture_cards, fixture_pack_config, FirstAvailablePickSource())

    def second_pick_pack_id(round_number: int, seat: int) -> str:
        return next(
            str(e.payload["pack_id"])
            for e in store.events
            if e.type == "PICK_MADE"
            and e.round == round_number
            and e.seat == seat
            and e.pick_number == 2
        )

    # "left" (rounds 1 and 3): seat 0's second pick comes from seat 7's
    # opened pack (r{round}p7) - seat 0 receives from its right-hand
    # neighbor when everyone passes left.
    assert second_pick_pack_id(1, 0) == "r1p7"
    assert second_pick_pack_id(3, 0) == "r3p7"
    # "right" (round 2): seat 0 receives from seat 1 instead.
    assert second_pick_pack_id(2, 0) == "r2p1"


async def test_round_duration_matches_plan_section_2_2(
    fixture_cards: list[Card], fixture_pack_config: PackConfig
) -> None:
    _, store = await _run(fixture_cards, fixture_pack_config, FirstAvailablePickSource())
    for round_number in (1, 2, 3):
        pack_opened = next(
            e
            for e in store.events
            if e.type == "PACK_OPENED" and e.round == round_number and e.seat == 0
        )
        round_complete = next(
            e for e in store.events if e.type == "ROUND_COMPLETE" and e.round == round_number
        )
        assert round_complete.ts_sim_ms - pack_opened.ts_sim_ms == 360_000


async def test_review_window_advances_the_clock_when_not_skipped(
    fixture_cards: list[Card], fixture_pack_config: PackConfig
) -> None:
    state, store = await run_draft(
        session_id="review-test",
        seed="review-seed",
        cards=fixture_cards,
        pack_config=fixture_pack_config,
        pick_source=FirstAvailablePickSource(),
        skip_review=False,
        review_window_seconds=60,
    )
    assert state.phase == "finished"
    review_opened = next(e for e in store.events if e.type == "REVIEW_OPENED" and e.round == 1)
    review_closed = next(e for e in store.events if e.type == "REVIEW_CLOSED" and e.round == 1)
    assert review_opened.payload["skipped"] is False
    assert review_closed.ts_sim_ms - review_opened.ts_sim_ms == 60_000


async def test_simclock_full_draft_completes_well_under_two_seconds(
    fixture_cards: list[Card], fixture_pack_config: PackConfig
) -> None:
    start = time.perf_counter()
    await _run(fixture_cards, fixture_pack_config, FirstAvailablePickSource())
    assert time.perf_counter() - start < 2.0


async def test_same_seed_and_pick_source_gives_identical_events(
    fixture_cards: list[Card], fixture_pack_config: PackConfig
) -> None:
    source = FirstAvailablePickSource()
    _, store_a = await _run(fixture_cards, fixture_pack_config, source, seed="det")
    _, store_b = await _run(fixture_cards, fixture_pack_config, source, seed="det")

    def strip_wall_time(e: DraftEvent) -> dict[str, Any]:
        d = e.model_dump(mode="json", by_alias=True)
        d.pop("ts_wall")
        return d

    events_a = [strip_wall_time(e) for e in store_a.events]
    events_b = [strip_wall_time(e) for e in store_b.events]
    assert events_a == events_b


async def test_timeout_produces_pick_auto_with_no_response_reason(
    fixture_cards: list[Card], fixture_pack_config: PackConfig
) -> None:
    source = SeatSpecificPickSource(flaky_seat=3, flaky_source=AlwaysTimesOutPickSource())
    state, store = await _run(fixture_cards, fixture_pack_config, source)
    autos = [e for e in store.events if e.type == "PICK_AUTO"]
    assert len(autos) == 14 * 3  # every pick, every round, for seat 3 only
    assert all(e.seat == 3 for e in autos)
    assert all(e.payload["reason"] == "no_response" for e in autos)
    assert all(e.payload["timed_out"] is True for e in autos)
    assert state.timeout_count == 42
    assert len(state.seat_pools[3]) == 42  # still gets a full pool via auto-pick


async def test_invalid_decision_produces_pick_auto_with_invalid_decision_reason(
    fixture_cards: list[Card], fixture_pack_config: PackConfig
) -> None:
    source = SeatSpecificPickSource(flaky_seat=5, flaky_source=InvalidPickSource())
    _, store = await _run(fixture_cards, fixture_pack_config, source)
    autos = [e for e in store.events if e.type == "PICK_AUTO" and e.seat == 5]
    assert len(autos) == 42
    assert all(e.payload["reason"] == "invalid_decision" for e in autos)


async def test_auto_picked_card_is_always_from_the_offered_pack(
    fixture_cards: list[Card], fixture_pack_config: PackConfig
) -> None:
    source = SeatSpecificPickSource(flaky_seat=2, flaky_source=AlwaysTimesOutPickSource())
    _, store = await _run(fixture_cards, fixture_pack_config, source)
    for e in store.events:
        if e.type == "PICK_AUTO" and e.seat == 2:
            assert e.payload["picked_uid"] in e.payload["offered_uids"]


async def test_extras_removed_matches_non_draftable_slot_count(
    fixture_cards: list[Card], fixture_pack_config: PackConfig
) -> None:
    _, store = await _run(fixture_cards, fixture_pack_config, FirstAvailablePickSource())
    for e in store.events:
        if e.type == "EXTRAS_REMOVED":
            assert len(e.payload["extras_uids"]) == 2  # basic + chase slots, S9


async def test_no_event_payload_references_another_seats_identity(
    fixture_cards: list[Card], fixture_pack_config: PackConfig
) -> None:
    """plan section 6.2 invariant: 'No event ever contains another seat's
    pool.' PACK_PASSED's `from_seat` names a neighboring seat, but only as
    pack-circulation metadata (never that seat's pool/pick) - this is the
    engine's own append-only ground truth, not something handed to an
    agent (that filtering is WP-08's job). Every *other* event type must
    only ever reference `event.seat` itself.
    """
    _, store = await _run(fixture_cards, fixture_pack_config, FirstAvailablePickSource())
    for e in store.events:
        if e.type == "PACK_PASSED":
            continue
        if e.type == "POOL_FINALIZED":
            assert set(e.payload.keys()) == {"total_drafted"}
            continue
        if e.seat is None:
            continue
        # None of these payloads carry a `seat`-shaped field naming a
        # different seat.
        payload_str = json.dumps(e.payload)
        for other_seat in range(8):
            if other_seat == e.seat:
                continue
            assert f'"seat": {other_seat}' not in payload_str


@pytest.mark.skipif(
    not IAR_SET_PATH.exists(), reason="real IAR data not ingested in this environment"
)
async def test_real_iar_data_end_to_end() -> None:
    cards = SetSnapshot.model_validate(json.loads(IAR_SET_PATH.read_text())).cards
    pack_config = PackConfig.model_validate(json.loads(IAR_PACK_CONFIG_PATH.read_text()))
    state, _ = await _run(cards, pack_config, FirstAvailablePickSource(), seed="real-data-wp07")
    assert state.phase == "finished"
    assert {len(p) for p in state.seat_pools.values()} == {42}
